# Generated by Django 3.1.2 on 2020-10-20 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=250, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cidade', models.CharField(max_length=250, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=250, verbose_name='Bairro')),
                ('rua', models.CharField(max_length=250, verbose_name='Rua')),
                ('numero', models.CharField(max_length=20, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, max_length=300, null=True, verbose_name='Complemento')),
                ('salario', models.FloatField(verbose_name='Salario')),
            ],
            options={
                'verbose_name': 'Corretor',
                'verbose_name_plural': 'Corretores',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=250, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cidade', models.CharField(max_length=250, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=250, verbose_name='Bairro')),
                ('rua', models.CharField(max_length=250, verbose_name='Rua')),
                ('numero', models.CharField(max_length=20, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, max_length=300, null=True, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Inquilino',
                'verbose_name_plural': 'Inquilinos',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=250, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cidade', models.CharField(max_length=250, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=250, verbose_name='Bairro')),
                ('rua', models.CharField(max_length=250, verbose_name='Rua')),
                ('numero', models.CharField(max_length=20, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, max_length=300, null=True, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Proprietario',
                'verbose_name_plural': 'Proprietarios',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('valor_aluguel', models.FloatField(verbose_name='Valor do Aluguel')),
                ('alugado', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Alugado')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proprietario')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
            },
        ),
        migrations.CreateModel(
            name='Contactar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data e hora de atendimento')),
                ('corretor', models.ManyToManyField(to='core.Corretor')),
                ('proprietario', models.ManyToManyField(to='core.Proprietario')),
            ],
            options={
                'verbose_name': 'Contatar',
                'verbose_name_plural': 'Contatars',
            },
        ),
        migrations.CreateModel(
            name='Atende',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data e hora de atendimento')),
                ('corretor', models.ManyToManyField(to='core.Corretor')),
                ('inquilino', models.ManyToManyField(to='core.Inquilino')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
        migrations.CreateModel(
            name='Alugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aluguel', models.DateField(verbose_name='Data do aluguel')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corretor')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imovel')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inquilino')),
            ],
            options={
                'verbose_name': 'Alugado',
                'verbose_name_plural': 'Alugados',
            },
        ),
    ]
