# Generated by Django 3.1.2 on 2020-10-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atende',
            name='data',
            field=models.DateField(verbose_name='Data e hora de atendimento'),
        ),
        migrations.AlterField(
            model_name='contactar',
            name='data',
            field=models.DateField(verbose_name='Data e hora de atendimento'),
        ),
    ]
